### PR TITLE
Update params_calibnet.go

### PR DESCRIPTION
**Pull request by Fatman13**
Propose new upgrade time for EverythingBurns

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [ ] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by 88phnx88** [comment]
@Fatman13 提议的时间与官方时间冲突: [filecoin-project/community/discussions/74](https://github.com/filecoin-project/community/discussions/74#discussioncomment-10881951) 。 这是故意的吗？无论如何，我们都支持你。请确认 `2077594`，我们将对所有地方进行调整。

**Comment by Fatman13** [comment]
应该不项目方的升级时间要早 10 个小时，这样会造成冲突吗？因为我对升级底层技术逻辑还不是最清楚。😂

**Comment by Fatman13** [comment]
主要是想给矿工们更多的准备和思考的时间。

**Comment by 88phnx88** [comment]
> 因为我对升级底层技术逻辑还不是最清楚。😂

@Fatman13 您的更改已应用，并附带更好的解释：https://github.com/88phnx88/lotus/blob/master/README.md#everythingburns

> 主要是想给矿工们更多的准备和思考的时间。

✔️

**Pull request closed without merging**
